### Get All Certificates
GET http://localhost:8080/certificates
Content-Type: application/json

###

### Get Single Certificate by ID
GET http://localhost:8080/certificates/66a02fcfc58a72f6d4cd6351
Content-Type: application/json

###

### Create a New Certificate
POST http://localhost:8080/certificates/create
Content-Type: application/json

{
    "name": "Information Technology",
    "description": "A certificate in information technology.",
    "requirements": ["Complete all core courses", "Complete a capstone project"],
    "courseType": "Core"
}

###

### Update a Certificate by ID
PUT http://localhost:8080/certificates/
Content-Type: application/json

{
  "degree": "66a02fcfc58a72f6d4cd634f",
  "courses": ["66a02fcfc58a72f6d4cd634c"]
}

###

### Delete a Certificate
DELETE http://localhost:8080/certificates/delete/cert-software-development
Content-Type: application/json
