# Localhost

# DEGREE #
###
# GET ALL
GET http://localhost:8080/courses HTTP/1.1

###
# GET BY ID
GET http://localhost:8080/courses/course-bus101 HTTP/1.1

###

#Update by ID
POST http://localhost:8080/courses/ HTTP/1.1
Content-Type: application/json

{
  "_id": "course-bus101",
  "name": "Introduction to Business",
  "code": "BUS101",
  "description": "An introductory course to business principles.",
  "credits": 3,
  "certificate": "cert-business",
  "degree": "sftdev-byui",
  "courseType": "Core"
}

###
# Delete BY ID
DELETE  http://localhost:8080/courses/