# Localhost

# DEGREE #
###
# GET ALL
GET http://localhost:8080/degrees

###
# GET BY ID
GET http://localhost:8080/degrees/sftdev-byui

###

POST http://localhost:8080/degrees/create HTTP/1.1
Content-Type: application/json

{
    "_id": "sftdev-byui",
    "name": "Associate of Science in Business",
    "institutions": "byui-pw",
    "type": "Associate",
    "description": "An associate degree focused on business principles.",
    "potentialEmployment": ["Business Analyst", "Marketing Coordinator"],
    "duration": "2 years",
    "creditsRequired": 60,
    "level": "Undergraduate",
    "certificates": "cert-business"
}

###


#Update by ID
PUT http://localhost:8080/degrees/update/6692d76a6686128f9b89a8ed HTTP/1.1
Content-Type: application/json

{
    "type": "Online"
}

###
# Delete BY ID
DELETE  http://localhost:8080/degrees/delete/668d35ad3911a672d32e22ea


# INSTITUTION #

###
# GET ALL
GET http://localhost:8080/institution

###

# GET BY ID
GET http://localhost:8080/institution/6692daa86686128f9b8ae061

###

#Update by ID
PUT http://localhost:8080/institution/update/668e8721fc87859b5a89402c HTTP/1.1
Content-Type: application/json

{
    "name": "Brigham Young University - Idaho"
}

###

# Delete BY ID
DELETE  http://localhost:8080/institution/delete/668e87d5fc87859b5a89402e

###
