### Get All Users
GET http://localhost:8080/users
Content-Type: application/json

###

### Get Single User by ID
GET http://localhost:8080/users/stdntf-admin
Content-Type: application/json

###

### Create a New User
POST http://localhost:8080/users
Content-Type: application/json

{
  "_id": "stdnte-instr",
   "username": "eve_instructor",
  "email": "eve@example.com",
  "password": "password123",
  "role": "instructor"
}

###

### Update a User by Admin
PUT http://localhost:8080/users/stdntf-admin
Content-Type: application/json

{
  "username": "john_doe_updated",
  "email": "john.doe.updated@example.com",
  "role": "dev"
}

###

### Update My Profile (Non-Admin Users)
PUT http://localhost:8080/users/me/669a7128bd0ed9470bcde9f0
Content-Type: application/json

{
  "username": "john_doe_updated",
  "email": "john.doe.updated@example.com"
}

###

### Delete a User
DELETE http://localhost:8080/users/669a7333bd0ed9470bcde9f6
Content-Type: application/json

# [
#   {
#     "username": "alice_wonder",
#     "email": "alice@example.com",
#     "password": "password123",
#     "role": "student"
#   },
#   {
#     "username": "bob_builder",
#     "email": "bob@example.com",
#     "password": "password123",
#     "role": "dev"
#   },
#   {
#     "username": "charlie_chaplin",
#     "email": "charlie@example.com",
#     "password": "password123",
#     "role": "student"
#   },
#   {
#     "username": "dave_dev",
#     "email": "dave@example.com",
#     "password": "password123",
#     "role": "dev"
#   },
#   {
#     "username": "eve_instructor",
#     "email": "eve@example.com",
#     "password": "password123",
#     "role": "instructor"
#   },
#   {
#     "username": "frank_admin",
#     "email": "frank@example.com",
#     "password": "adminpassword",
#     "role": "admin"
#   },
#   {
#     "username": "grace_student",
#     "email": "grace@example.com",
#     "password": "password123",
#     "role": "student"
#   }
# ]
